"""Add processed_display_name with a FULLTEXT index

Revision ID: 51e356c6f5fb
Revises: 
Create Date: 2017-05-13 06:46:33.054469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51e356c6f5fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nyaa_torrents', sa.Column('processed_display_name', sa.String(length=255, collation='utf8_general_ci'), nullable=False))
    op.execute('ALTER TABLE nyaa_torrents ADD FULLTEXT (processed_display_name)') # Fulltext
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('processed_display_name'), table_name='nyaa_torrents')
    op.drop_column('nyaa_torrents', 'processed_display_name')
    # ### end Alembic commands ###
